// frontend/src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; // 1. Import the AuthProvider
import Header from "@/components/Header"; // 1. Import the Header

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 2. Wrap the children with the AuthProvider */}
        <AuthProvider>
          <Header /> {/* 2. Add the Header component here */}
          <main>{children}</main> {/* It's good practice to wrap main content in a <main> tag */}
        </AuthProvider>
      </body>
    </html>
  );
}