version: '3.8'
services:
  db:
    image: postgres:15 # Or a more recent stable version
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # Maps port 5433 on your host to port 5432 in the container
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists data even if container stops

volumes:
  postgres_data: # Defines the named volume